package domain;

/**
 * a factory for player objects, each player generated by {@link #create(String)} is guaranteed
 * to have a unique identifier and color.
 * @author rverbist
 */
public final class PlayerFactory
{
    private static final PlayerFactory _instance = new PlayerFactory();

    public static final PlayerFactory getInstance()
    {
        return _instance;
    }

    private int _identifier;
    private GoldenRatioColorGenerator _colors;

    private PlayerFactory()
    {
        _identifier = 0;
        _colors = new GoldenRatioColorGenerator(0.5f, 0.95f);
    }

    /**
     * creates an unique player object with the given name.
     * @param name the name of the player
     * @return a player
     */
    public synchronized Player create(final String name)
    {
        return new Player(_identifier++, name, _colors.next());
    }
}
